import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.scss";
import { Header } from "@/components/Header/header";
import { Footer } from "@/components/Footer/footer";
import { DataProvider } from "@/context/product";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "MKS Sistemas",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <DataProvider>
          <Header />
            {children}
          <Footer />
        </DataProvider>
      </body>
    </html>
  );
}
